In [ ]:
import pandas as pd 
import numpy as np 
messages = (
    pd.read_csv('archive/spam.csv', encoding = 'latin-1')
    .rename(columns= {'v1' : 'label' , 'v2' : 'message'})
    [['label', 'message']]
)
messages.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [17]:
import nltk 
import re
from nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer 
lemetizer = WordNetLemmatizer()

In [18]:
corpus = [ ]
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i] )
    review = review.lower()
    review = review.split()
    review = [ lemetizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
corpus 

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000 , binary= True , ngram_range=(3, 3))
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
cv.vocabulary_

{'free entry wkly': np.int64(267),
 'std txt rate': np.int64(763),
 'txt rate apply': np.int64(868),
 'melle melle oru': np.int64(519),
 'melle oru minnaminunginte': np.int64(520),
 'minnaminunginte nurungu vettam': np.int64(538),
 'set callertune caller': np.int64(713),
 'callertune caller press': np.int64(90),
 'caller press copy': np.int64(88),
 'press copy friend': np.int64(645),
 'copy friend callertune': np.int64(162),
 'call claim code': np.int64(70),
 'entitled update latest': np.int64(225),
 'update latest colour': np.int64(880),
 'free call mobile': np.int64(262),
 'call mobile update': np.int64(80),
 'mobile update co': np.int64(557),
 'update co free': np.int64(879),
 'chance win cash': np.int64(115),
 'reply hl info': np.int64(676),
 'lt gt inch': np.int64(471),
 'message missed call': np.int64(523),
 'like lt gt': np.int64(437),
 'lt url gt': np.int64(483),
 'special cinema pas': np.int64(745),
 'suprman matrix starwars': np.int64(784),
 'matrix starwars etc': np.int64(51

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features= 100)
X = vectorizer.fit_transform(corpus).toarray()

In [29]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
import pandas as pd 
import numpy as np 
import sklearn.model_selection as  ms
import nltk 
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem import PorterStemmer 